"""Behavioral analysis - measures skill formation vs atrophy over time."""

from praxis.behavior.cadence import (
    DEFAULT_STREAK_WINDOW_DAYS,
    HIGH_STREAK_RATIO,
    LOW_STREAK_RATIO,
    MIN_ELAPSED_SECONDS,
    MIN_USER_TURNS,
    HighAdopterPosition,
    compute_weekday_streak,
    high_adopter_position,
    is_substantive_session,
)
from praxis.behavior.headline import (
    HEADLINE_MAX_CHARS,
    fallback_headline,
    generate_headline,
)
from praxis.behavior.labels import (
    HYSTERESIS_STDERR_MULTIPLIER,
    MIN_BUCKETS_FOR_LABEL,
    WeeklyTrajectoryLabel,
    apply_hysteresis,
    is_strongly_significant,
    label_from_fit,
    label_trajectory,
    label_trajectory_with_hysteresis,
)
from praxis.behavior.repeat_task import (
    MIN_OTHER_CLUSTERS_FOR_REPEAT,
    MIN_TOKENS_FOR_COMPARISON,
    OVERLAP_THRESHOLD,
    STOPWORDS,
    Cluster,
    RepeatTask,
    detect_repeats,
    overlap_ratio,
    tokenize,
)
from praxis.behavior.signals import BehavioralSignals, extract
from praxis.behavior.slope import (
    SIGNIFICANCE_MIN_SLOPE_PER_WEEK,
    SIGNIFICANCE_STDERR_MULTIPLIER,
    SlopeFit,
    WeeklyTrajectoryFit,
    fit_metric,
    fit_weekly_trajectory,
)
from praxis.behavior.trajectory import (
    TrajectoryAssessment,
    TrajectoryLabel,
    assess,
)
from praxis.behavior.weekly import (
    DEFAULT_WINDOW_DAYS,
    MIN_SESSIONS_FOR_FIT,
    WeeklyBucket,
    WeeklySessionInput,
    bucket_sessions_by_iso_week,
    iso_week_start,
    iso_week_tag,
)

__all__ = [
    "DEFAULT_STREAK_WINDOW_DAYS",
    "DEFAULT_WINDOW_DAYS",
    "HEADLINE_MAX_CHARS",
    "HIGH_STREAK_RATIO",
    "HYSTERESIS_STDERR_MULTIPLIER",
    "LOW_STREAK_RATIO",
    "MIN_BUCKETS_FOR_LABEL",
    "MIN_ELAPSED_SECONDS",
    "MIN_OTHER_CLUSTERS_FOR_REPEAT",
    "MIN_SESSIONS_FOR_FIT",
    "MIN_TOKENS_FOR_COMPARISON",
    "MIN_USER_TURNS",
    "OVERLAP_THRESHOLD",
    "SIGNIFICANCE_MIN_SLOPE_PER_WEEK",
    "SIGNIFICANCE_STDERR_MULTIPLIER",
    "STOPWORDS",
    "BehavioralSignals",
    "Cluster",
    "HighAdopterPosition",
    "RepeatTask",
    "SlopeFit",
    "TrajectoryAssessment",
    "TrajectoryLabel",
    "WeeklyBucket",
    "WeeklySessionInput",
    "WeeklyTrajectoryFit",
    "WeeklyTrajectoryLabel",
    "apply_hysteresis",
    "assess",
    "bucket_sessions_by_iso_week",
    "compute_weekday_streak",
    "detect_repeats",
    "extract",
    "fallback_headline",
    "fit_metric",
    "fit_weekly_trajectory",
    "generate_headline",
    "high_adopter_position",
    "is_strongly_significant",
    "is_substantive_session",
    "iso_week_start",
    "iso_week_tag",
    "label_from_fit",
    "label_trajectory",
    "label_trajectory_with_hysteresis",
    "overlap_ratio",
    "tokenize",
]
